import Cache from './sq-profile-cache.interface'

export interface Instagram {
  id: string
  user_id?: string
  username: string
  exists: boolean
  searchable: number
  macro: number
  notSearchReason: string
  brandUser: number
  picture: string
  fullName: string
  email: string
  bio?: string
  website?: string
  language?: string
  isBusiness: number
  hasSkip?: number
  facebookUserId: string
  facebookPageId: string
  instagramBusinessId: string
  scrapperEngagementRate: number
  engagementRate?: number
  totalMedias: number
  medias: number
  followers: number
  follows: number
  likes: number
  comments: number
  tier: string
  createdAt: string
  updatedAt: string
  logstashProcessedAt: any
  score?: number
  score1?: number
  score2?: number
  score3?: number
  score4?: number
  score5?: number
  storiesEngagementRate?: number
  postEffectiveReach?: number
  storiesEffectiveReach?: number
  profileViews: number
  hasMediaKit: number
  categorizedAt?: string
  averageComments: number
  averageCommentsImage: number
  averageCommentsVideo: number
  averageCommentsCarousel: number
  averageLikes: number
  averageLikesImage: number
  averageLikesVideo: number
  averageLikesCarousel: number
  commentLikesRate: number
  commentsRate: number
  totalStoriesImpressions?: number
  totalStoriesReach?: number
  totalStoriesReplies?: number
  totalStoriesTapBacks?: number
  totalStoriesTapFowardExits: number
  totalPostsReach?: number
  totalPostsSaves?: number
  totalPostsImpressions?: number
  averageSaved: number
  averageSavedImage: number
  averageSavedVideo: number
  averageSavedCarousel: number
  averageTapBacks: number
  averageTapBacksImage: number
  averageTapBacksVideo: number
  averageReplies: number
  averageRepliesImage: number
  averageRepliesVideo: number
  averageTapFowardExits: number
  averageTapFowardExitsImage: number
  averageTapFowardExitsVideo: number
  completeVideoStoriesRate: number
  numberPostsActivityScore?: number
  numberStoriesScore?: number
  daysPostsScore?: number
  daysStoriesScore?: number
  advertisingPostsEngagementRate?: number
  noAdvertisingPostsEngagementRate?: number
  advertisingStoriesEngagementRate?: number
  noAdvertisingStoriesEngagementRate?: number
  advertisingContentPercentage?: number
  advertisingPostsPercentage?: number
  advertisingStoriesPercentage?: number
  postImageEngagementRate?: number
  postCarouselEngagementRate?: number
  postVideoEngagementRate?: number
  storiesVideoEngagementRate?: number
  storiesImageEngagementRate?: number
  storiesCompleteEngagementRate?: number
  averagePostsReach: number
  averagePostsImpressions: number
  averagePostsFrequency: number
  averageStoriesReach: number
  averageStoriesImpressions: number
  averageStoriesFrequency: number
  adPostPermanceEngagementRate?: number
  adStoriesPermanceEngagementRate?: number
  identifyAt?: string
  socialNetworkProfilesCache?: Cache[]
}

export interface Youtube {
  id: string
  googleId: string
  exists: boolean
  searchable: number
  notSearchReason: string
  email: string
  channelTitle: string
  username: string
  picture: string
  fullName: string
  description: any
  bio?: string
  customUrl: string
  country: string
  since: string
  followers: number
  subscribers: number
  engagementRate?: number
  engagementRatePositive: number
  engagementRateNegative: number
  viewsRate: number
  viewsMedian: number
  comments: number
  identificationComments: number
  identificationLikes: number
  identificationDislikes: number
  averageComments: number
  averageLikes: number
  averageDislikes: number
  shares: number
  averageShares: number
  commentLikesRate: number
  commentViewsRate: number
  averageViewsDuration: number
  averageViewPercentage: number
  averageVideoDuration: number
  videoEffectiveReach: number
  videos: number
  identificationVideos: number
  views: number
  identificationViews: number
  privacyStatus: string
  language?: string
  createdAt: string
  updatedAt: string
  logstashProcessedAt: any
  macro: number
  brandUser: number
}
export interface Twitter {
  id: string
  username: string
  picture: string
  followers: number
  createdAt: string
  updatedAt: string
  brandUser: number
  exists: boolean
  macro: number
  engagementRate?: number
  totalRetweets: number
  totalLikes: number
  totalRetweetsReceived: number
  averageLikes: number
  averageRetweets: number
  totalTweets: number
  averageRepliesByLikes: number
  averageRepliesByTweet: number
  repliesRate: number
  effectiveImpressionReach: number
  averageImpressions: number
  countReplies: number
  adTweetsCount: number
  engagementRateAd: number
  tweetPostAdPerformance: number
}
export interface TikTok {
  id: string
  openId: string
  unionId: string
  exists: boolean
  verified: boolean
  username: string
  nickname: string
  macro: number
  brandUser: number
  picture: string
  bio?: string
  engagementRate?: number
  followers: number
  following: number
  likes: number
  averageLikes: number
  comments: number
  averageComments: number
  shares: number
  averageShares: number
  views: number
  averageViews: number
  createdAt: string
  updatedAt: string
  isValid: boolean
  status: any
}
